- hosts: localhost
  become: true
  tasks:
  - name: Create new databases with names 'foo' and 'bar'
    community.mysql.mysql_db:
      name:
      - foo
      - bar
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock

  - name: Dump all databases to hostname.sql including master data
    community.mysql.mysql_db:
      state: dump
      name: all
      target: /tmp/dump.sql
      master_data: 1
      login_unix_socket: /run/mysqld/mysqld.sock

  - name: Copy database dump file
    ansible.builtin.copy:
      src: /tmp/dump.sql
      dest: /tmp

- hosts: server2
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Copy database dump file
    ansible.builtin.copy:
      src: /tmp/dump.sql
      dest: /tmp

  - name: Change to a specific directory and backup
    ansible.builtin.shell:
      cmd: "cd /tmp/ && mysql -u root -pvagrant < dump.sql"
